### ISSUE TITLE
holy shit

### ISSUE THREAD

**Issue by damusix** [fauxsoup/otp-js#1]
This is fucking awesome. What happened to this idea?!

**Comment by soup-in-boots** [comment]
I haven't had the time to follow through on this, though the basic building blocks are in place.

**Comment by damusix** [comment]
Im learning erlang / elixir now. Any way I can help? I'm good with JS.

**Comment by damusix** [comment]
This kinda got my mind going. I was thinking that, maybe, instead of trying to mimic erlang otp 100%, why not just mimic the send / receive messages across threads + supervision / genserver functionality _only_ instead of also trying to pass functions, classes and their state? Seems like that might be difficult (or impossible) given Node limitations, especially given that Erlang can communicate across a network to other compute resources, whereas Node is isolated to a single compute resource.

Maybe the instantiation of state on functions / classes can be managed by the developer as messages come in instead of attempting to recover a hashed state. And perhaps the networking aspect can be accomplished via streaming on a socket, where you would make your processes aware of each other using an array of IPs or DNS names.

**Comment by soup-in-boots** [comment]
I'll welcome any pull requests you want to make. You've got a point that it doesn't make sense to try to implement features like function passing; it was fun to investigate, but ultimately fruitless.

It would be worth implementing the suite of process patterns if you're looking for something to do. I'm not sure how much time I'll have to devote to this, but it is a fun project and I should pick it up again soon.

**Comment by soup-in-boots** [comment]
I'm going to close this issue. I've made some significant changes based on your recommendations and would be curious as to your thoughts. Communication across threads would require an adapter that I haven't implemented, but this may be a better model for moving forward.

**Comment by damusix** [comment]
Yep that seems to make more sense. Send the process a message -> deal with the payload without trying to re-instantiate things.

It would make sense to implement something like a BEAM scheduler. That could be a process that lives in the master cluster that cycles through child processes and sends an even distribution of work to them. Not 100% sure if you can dictate what CPU a process uses, but if you can, would probably be helpful. Multicore node would be dope.

Also, maybe an ETS table implementation to go along with the scheduler. This would allow sharing of state across the cluster without duplicating memory in each process. This can be a simple map, and should be good for up to 1.75 GB by default or more with `--max_old_space_size=`. All it does is get and set. I built [this thing](https://www.npmjs.com/package/memory-cache2), not sure if it'll help, or help get that started.

BTW, you move fast AF lol. I'd like to help on my spare time. Can we setup a little kanban sprint board or something here on github?
